version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: "VM env details"
          command: ./whatsit.sh
      - run:
          name: "Try out Docker"
          command: docker build -t dancarbone/circle-ci-test:latest -f Dockerfile .