version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: "VM env details"
          command: ./whatsit.sh
      - run:
          name: "can has build?"
          command: docker build -t dancarbone/circle-ci-test:latest -f Dockerfile .
      - run:
          name: "can has run?"
          command: docker run -u $(id -u):$(id -g) dancarbone/circle-ci-test:latest whatsit.sh
  dostuff:
    docker:
      - image: dancarbone/circle-ci-test:latest
    steps:
      - run:
          name: "i dunno does this work?"
          command: whatsit.sh