version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Testing"
          command: ./whatsit.sh